import { useEffect, useState } from 'react';
import { Dialog } from './ui/Dialog';
import { Icon } from '../icons';
import { fetchDeviceLogs, type DeviceOperationLog } from '../lib/deviceLogs';

interface DeviceLogsDialogProps { entityId: string; deviceName: string; onClose: () => void; }
function formatTime(value: string): string { const date = new Date(value); if (!Number.isFinite(date.getTime())) return '时间未知'; return new Intl.DateTimeFormat('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit' }).format(date); }
function sourceLabel(log: DeviceOperationLog): string { if (log.source === 'automation') return log.automation_name ? `自动化 · ${log.automation_name}` : '自动化'; if (log.source === 'manual') return log.actor === 'admin' ? '管理员手动操作' : '用户手动操作'; return '系统'; }
function actionLabel(log: DeviceOperationLog): string { const data = log.metadata?.service_data; if (log.action === 'climate.set_hvac_mode') { const mode = typeof data === 'object' && data && 'hvac_mode' in data ? String(data.hvac_mode) : ''; if (mode === 'off') return '关闭空调'; if (mode === 'cool') return '开启空调并切换为制冷模式'; return mode ? `开启空调并切换为${mode}模式` : '开启空调'; } if (log.action === 'climate.set_temperature') { const temperature = typeof data === 'object' && data && 'temperature' in data ? String(data.temperature) : ''; return temperature ? `设置温度 · ${temperature}°C` : '设置空调温度'; } if (log.action === 'climate.set_fan_mode' || log.action === 'select.select_option') { const value = typeof data === 'object' && data && ('fan_mode' in data || 'option' in data) ? String('fan_mode' in data ? data.fan_mode : data.option) : ''; return value ? `调整风速 · ${value}` : '调整风速'; } if (log.action === 'cover.open_cover') return '打开'; if (log.action === 'cover.close_cover') return '关闭'; if (log.action === 'cover.stop_cover') return '停止'; if (log.action === 'cover.set_cover_position') return '调整开合度'; if (log.action === 'light.turn_on' || log.action === 'switch.turn_on') return '开启'; if (log.action === 'light.turn_off' || log.action === 'switch.turn_off') return '关闭'; return log.action; }

export function DeviceLogsDialog({ entityId, deviceName, onClose }: DeviceLogsDialogProps) {
  const [logs, setLogs] = useState<DeviceOperationLog[] | null>(null); const [error, setError] = useState<string | null>(null); const [syncing, setSyncing] = useState(true);
  useEffect(() => { let cancelled = false; fetchDeviceLogs(entityId).then((value) => { if (!cancelled) { setLogs(value); setSyncing(false); } }).catch((reason) => { if (!cancelled) { setError(reason instanceof Error ? reason.message : '设备日志读取失败'); setSyncing(false); } }); return () => { cancelled = true; }; }, [entityId]);
  let content;
  if (error) content = <div className="device-logs-state is-error" role="alert"><Icon name="alert-triangle" size={18} />{error}</div>;
  else if (logs === null) content = <div className="device-logs-state"><span className="session-loading__spinner" />正在加载日志…</div>;
  else if (logs.length === 0) content = <div className="device-logs-state"><Icon name="folder" size={20} /><strong>暂无操作记录</strong><span>该设备还没有通过看板产生可追踪的操作。</span></div>;
  else content = <><div className="device-logs-list">{logs.map((log) => <article className="device-log-item" key={log.id}><span className={`device-log-item__dot${log.success ? '' : ' is-failed'}`} aria-hidden="true" /><div className="device-log-item__body"><div className="device-log-item__top"><strong>{actionLabel(log)}</strong><time dateTime={log.occurred_at}>{formatTime(log.occurred_at)}</time></div><div className="device-log-item__meta"><span className={`device-log-source${log.source === 'automation' ? ' is-automation' : ''}`}>{log.source === 'automation' && <Icon name="clock" size={12} />}{sourceLabel(log)}</span>{!log.success && <span className="device-log-failed">执行失败</span>}</div>{log.error_message && <p>{log.error_message}</p>}</div></article>)}</div>{syncing && <p className="device-logs-syncing"><span className="session-loading__spinner" />正在同步 Home Assistant 自动化记录…</p>}</>;
  return <Dialog title={`${deviceName} · 操作日志`} onClose={onClose} wide className="device-logs-dialog"><div className="device-logs-dialog__intro"><span className="device-logs-dialog__icon"><Icon name="clock" size={17} /></span><div><strong>设备操作记录</strong><span>{entityId}</span></div></div>{content}</Dialog>;
}
